# _data/config-metadata.yml
- field: objectid
  display_name: Object ID
- field: seriesnumber
  display_name: Series Number
- field: filename
  display_name: File Name

- field: title
  display_name: Title
- field: title_tib
  display_name: Title (Tibetan)
- field: title_eng
  display_name: Title (English)
- field: title_page_title
  display_name: Title Page Title
- field: title_page_title_tib
  display_name: Title Page Title (Tibetan)
- field: title_chi_pinyin
  display_name: 标题 (Pinyin)
- field: title_chi_characters
  display_name: 标题 (中文)

- field: bdrc_text_link
  display_name: BDRC Text Link
  external_link: true
- field: bdrc_author_link
  display_name: BDRC Author Link
  external_link: true
- field: tol_author_link
  display_name: TOL Author Link
  external_link: true

- field: author
  display_name: Author
- field: author_tib
  display_name: Author (Tibetan)
- field: author_phonetics
  display_name: Author (Phonetics)
- field: pub_year
  display_name: Publication Year
- field: ISBN
  display_name: ISBN
- field: bdrc_description
  display_name: BDRC Description
- field: location
  display_name: Location
- field: series
  display_name: Series
- field: rights
  display_name: Rights
- field: latitude
  display_name: Latitude
- field: longitude
  display_name: Longitude
